pipeline:
  name: Java Hello World CI
  identifier: Java_Hello_World_CI
  orgIdentifier: default        # e.g. default
  projectIdentifier: default_project # e.g. myproject
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.skpabbaGitHub  # GitHub connector ref
        repoName: harness-ci           # e.g. myusername/hello-world
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Build Test Push
        identifier: Build_Test_Push
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.minikubeskpabba  # K8s connector ref (Account-level delegate)
              namespace: harness-delegate            # namespace where your delegate runs
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Compile
                  identifier: Compile
                  spec:
                    connectorRef: account.Docker_Registry_SKPabba
                    image: maven:3.9-eclipse-temurin-17
                    shell: Sh
                    command: mvn compile -q

              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    connectorRef: account.Docker_Registry_SKPabba
                    image: maven:3.9-eclipse-temurin-17
                    shell: Sh
                    command: mvn test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "target/surefire-reports/**/*.xml"

              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to DockerHub
                  identifier: Build_and_Push
                  spec:
                    connectorRef: account.Docker_Registry_SKPabba
                    repo: skpabba/hello-world-java
                    tags:
                      - latest
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
                    optimize: true
